import type { AccountDetail } from './types';

export const MOCK_DETAILS: Record<string, AccountDetail> = {
  'acc-ria': {
    id: 'acc-ria',
    name: 'Retirement Income Account',
    memberNumber: '#ACC-235896',
    balance: 1289130.55,
    status: 'active',
    openedAt: '1 Jul 2024',
    paymentAmount: '$2,847.65',
    frequency: 'Fortnightly',
    nextPaymentDate: '15 Oct 2025',
    bankAccountName: 'Z O Oeter',
    bank: 'ANZ',
    bsb: '012-290',
    accountNumber: '******210',
    minimumPayment: '$39,240.00',
    paymentsToDate: '$34,712.52',
    beneficiaries: [
      { name: 'Janet Oeter', relationship: 'Spouse', share: '100%', type: 'binding' },
    ],
    centrelinkSchedule: [
      { date: '1 Jul 2025', grossAmount: '$34,171.80', taxFreeComponent: '$34,171.80', taxableComponent: '$0.00' },
      { date: '1 Jul 2026', grossAmount: '$35,025.60', taxFreeComponent: '$35,025.60', taxableComponent: '$0.00' },
      { date: '1 Jul 2027', grossAmount: '$35,901.24', taxFreeComponent: '$35,901.24', taxableComponent: '$0.00' },
    ],
    investmentAccount: {
      id: 'acc-002',
      name: 'Retirement Income account',
      accountNumber: '#ACC-235896',
      balance: 1289130.55,
      openedAt: '2024-07-01',
      isIncomeAccount: true,
    },
  },
  'acc-ria-2': {
    id: 'acc-ria-2',
    name: 'Retirement Income Account',
    memberNumber: '#ACC-235897',
    balance: 89130.55,
    status: 'active',
    openedAt: '15 Mar 2023',
    paymentAmount: '$1,509.24',
    frequency: 'Monthly',
    nextPaymentDate: '1 Nov 2025',
    bankAccountName: 'Z O Oeter',
    bank: 'Commonwealth Bank',
    bsb: '062-000',
    accountNumber: '******501',
    minimumPayment: '$18,600.00',
    paymentsToDate: '$12,480.00',
    beneficiaries: [
      { name: 'Samuel Oeter', relationship: 'Child', share: '50%', type: 'non-binding' },
      { name: 'Clara Oeter', relationship: 'Child', share: '50%', type: 'non-binding' },
    ],
    centrelinkSchedule: [
      { date: '1 Jul 2025', grossAmount: '$18,600.00', taxFreeComponent: '$18,600.00', taxableComponent: '$0.00' },
      { date: '1 Jul 2026', grossAmount: '$19,065.00', taxFreeComponent: '$19,065.00', taxableComponent: '$0.00' },
    ],
    investmentAccount: {
      id: 'acc-002',
      name: 'Retirement Income account',
      accountNumber: '#ACC-235897',
      balance: 89130.55,
      openedAt: '2023-03-15',
      isIncomeAccount: true,
    },
  },
  'acc-lp': {
    id: 'acc-lp',
    name: 'Lifetime Pension',
    memberNumber: '#ACC-235898',
    balance: 180.99,
    status: 'active',
    openedAt: '1 Jun 2026',
    paymentAmount: '$3,021.15',
    frequency: 'Fortnightly',
    nextPaymentDate: '30 Jun 2026',
    bankAccountName: 'Z O Oeter',
    bank: 'ANZ-Merged',
    bsb: '012-290',
    accountNumber: '******210',
    minimumPayment: '—',
    paymentsToDate: '$3,021.15',
    beneficiaries: [
      { name: 'Janet Oeter', relationship: 'Spouse', share: '100%', type: 'binding' },
    ],
    centrelinkSchedule: [
      { date: '1 Jul 2025', grossAmount: '$36,253.80', taxFreeComponent: '$36,253.80', taxableComponent: '$0.00' },
      { date: '1 Jul 2026', grossAmount: '$37,160.16', taxFreeComponent: '$37,160.16', taxableComponent: '$0.00' },
    ],
    investmentAccount: {
      id: 'acc-lp',
      name: 'Lifetime Pension',
      accountNumber: '#ACC-235898',
      balance: 180.99,
      openedAt: '2026-06-01',
      isIncomeAccount: true,
    },
  },
  'acc-ttr': {
    id: 'acc-ttr',
    name: 'Retirement Income Account',
    memberNumber: '#ACC-235899',
    balance: 0.77,
    status: 'active',
    openedAt: '12 Jan 2022',
    paymentAmount: '$500.00',
    frequency: 'Monthly',
    nextPaymentDate: '1 Nov 2025',
    bankAccountName: 'Z O Oeter',
    bank: 'Westpac',
    bsb: '032-000',
    accountNumber: '******789',
    minimumPayment: '$2,000.00',
    paymentsToDate: '$1,500.00',
    beneficiaries: [],
    centrelinkSchedule: [],
    investmentAccount: {
      id: 'acc-002',
      name: 'Retirement Income account',
      accountNumber: '#ACC-235899',
      balance: 0.77,
      openedAt: '2022-01-12',
      isIncomeAccount: true,
    },
  },
  'acc-closed-1': {
    id: 'acc-closed-1',
    name: 'Retirement Income Account',
    memberNumber: '#ACC-235900',
    balance: 0,
    status: 'closed',
    openedAt: '3 Feb 2018',
    paymentAmount: '$0.00',
    frequency: '—',
    nextPaymentDate: '—',
    bankAccountName: '—',
    bank: '—',
    bsb: '—',
    accountNumber: '—',
    minimumPayment: '—',
    paymentsToDate: '$0.00',
    beneficiaries: [],
    centrelinkSchedule: [],
    investmentAccount: {
      id: 'acc-closed-1',
      name: 'Retirement Income Account',
      accountNumber: '#ACC-235900',
      balance: 0,
      isIncomeAccount: true,
    },
  },
  'acc-closed-2': {
    id: 'acc-closed-2',
    name: 'Retirement Income Account',
    memberNumber: '#ACC-235901',
    balance: 0,
    status: 'closed',
    openedAt: '14 May 2015',
    paymentAmount: '$0.00',
    frequency: '—',
    nextPaymentDate: '—',
    bankAccountName: '—',
    bank: '—',
    bsb: '—',
    accountNumber: '—',
    minimumPayment: '—',
    paymentsToDate: '$0.00',
    beneficiaries: [],
    centrelinkSchedule: [],
    investmentAccount: {
      id: 'acc-closed-2',
      name: 'Retirement Income Account',
      accountNumber: '#ACC-235901',
      balance: 0,
      isIncomeAccount: true,
    },
  },
};
