import type { Application, IncomeAccount } from './types';

export const MOCK_INCOME_ACCOUNTS: IncomeAccount[] = [
  {
    id: 'acc-ria',
    name: 'Retirement Income Account',
    memberNumber: '235896',
    balance: 1289130.55,
    status: 'active',
    nextPaymentAmount: '$2,847.65',
    nextPaymentDate: '15 Oct 2025',
    icon: 'money-simple-from-bracket',
  },
  {
    id: 'acc-ria-2',
    name: 'Retirement Income Account',
    memberNumber: '235897',
    balance: 89130.55,
    status: 'active',
    nextPaymentAmount: '$2,847.65',
    nextPaymentDate: '15 Oct 2025',
    icon: 'money-simple-from-bracket',
  },
  {
    id: 'acc-lp',
    name: 'Lifetime Pension',
    memberNumber: '235898',
    balance: 180.99,
    status: 'active',
    nextPaymentAmount: '$3,021.15',
    nextPaymentDate: '30 Jun 2026',
    icon: 'money-check-dollar',
  },
  {
    id: 'acc-ttr',
    name: 'Retirement Income Account',
    memberNumber: '235899',
    balance: 0.77,
    status: 'active',
    nextPaymentAmount: '$500.00',
    nextPaymentDate: '1 Nov 2025',
    icon: 'money-simple-from-bracket',
  },
  {
    id: 'acc-closed-1',
    name: 'Retirement Income Account',
    memberNumber: '235900',
    balance: 0,
    status: 'closed',
    nextPaymentAmount: '—',
    nextPaymentDate: '—',
    icon: 'money-simple-from-bracket',
  },
  {
    id: 'acc-closed-2',
    name: 'Retirement Income Account',
    memberNumber: '235901',
    balance: 0,
    status: 'closed',
    nextPaymentAmount: '—',
    nextPaymentDate: '—',
    icon: 'money-simple-from-bracket',
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-001',
    accountType: 'Retirement Income Account',
    status: 'In progress',
    severity: 'info',
    startedAt: '10 Jun 2026',
    continuePath: '#',
  },
  {
    id: 'app-002',
    accountType: 'Lifetime Pension',
    status: 'Verification required',
    severity: 'warning',
    startedAt: '12 Jun 2026',
    continuePath: '/member-online/lifetime-pension/submitted',
  },
  {
    id: 'app-003',
    accountType: 'Transition to Retirement account',
    status: 'Submitted',
    severity: 'success',
    startedAt: '8 Jun 2026',
    continuePath: '/member-online/lifetime-pension/view-application',
  },
];
