import type { InvestmentAccount, InvestmentOption } from './types';

export const MOCK_ACCOUNTS: InvestmentAccount[] = [
  {
    id: 'acc-001',
    name: 'Accumulation account',
    accountNumber: '123 456 789',
    balance: 84250.0,
  },
  {
    id: 'acc-002',
    name: 'Transition to retirement account',
    accountNumber: '987 654 321',
    balance: 42100.5,
  },
];

export const MOCK_INVESTMENT_OPTIONS: InvestmentOption[] = [
  // Strategy options
  {
    id: 'opt-lifecycle',
    name: 'Lifecycle Investment Strategy',
    category: 'Strategy options',
    riskLevel: 'Varies by age',
    returnProfile: 'Varies by age',
    currentAllocation: 0,
    annualFee: 0.65, // representative blended rate; actual fee varies by age/pool split
  },
  // Diversified options
  {
    id: 'opt-high-growth',
    name: 'High Growth',
    category: 'Diversified options',
    riskLevel: 'High',
    returnProfile: 'High',
    currentAllocation: 40,
    annualFee: 0.70,
  },
  {
    id: 'opt-balanced',
    name: 'Balanced',
    category: 'Diversified options',
    riskLevel: 'Medium',
    returnProfile: 'Medium to high',
    currentAllocation: 60,
    annualFee: 0.65,
  },
  {
    id: 'opt-conservative-balanced',
    name: 'Conservative Balanced',
    category: 'Diversified options',
    riskLevel: 'Low to medium',
    returnProfile: 'Low to medium',
    currentAllocation: 0,
    annualFee: 0.63,
  },
  {
    id: 'opt-conservative',
    name: 'Conservative',
    category: 'Diversified options',
    riskLevel: 'Low',
    returnProfile: 'Low',
    currentAllocation: 0,
    annualFee: 0.60,
  },
  {
    id: 'opt-balanced-risk-adjusted',
    name: 'Balanced Risk-Adjusted',
    category: 'Diversified options',
    riskLevel: 'Medium',
    returnProfile: 'Medium',
    currentAllocation: 0,
    annualFee: 0.46,
  },
  {
    id: 'opt-socially-conscious',
    name: 'Socially Conscious Balanced',
    category: 'Diversified options',
    riskLevel: 'Medium',
    returnProfile: 'Medium to high',
    currentAllocation: 0,
    annualFee: 0.66,
  },
  {
    id: 'opt-high-growth-index',
    name: 'High Growth Index',
    category: 'Diversified options',
    riskLevel: 'High',
    returnProfile: 'High',
    currentAllocation: 0,
    annualFee: 0.08,
  },
  {
    id: 'opt-balanced-index',
    name: 'Balanced Index',
    category: 'Diversified options',
    riskLevel: 'Medium',
    returnProfile: 'Medium to high',
    currentAllocation: 0,
    annualFee: 0.08,
  },
  // Asset class options
  {
    id: 'opt-aus-shares',
    name: 'Australian Shares',
    category: 'Asset class options',
    riskLevel: 'High',
    returnProfile: 'High',
    currentAllocation: 0,
    annualFee: 0.08,
  },
  {
    id: 'opt-intl-shares-hedged',
    name: 'International Shares Hedged Index',
    category: 'Asset class options',
    riskLevel: 'High',
    returnProfile: 'High',
    currentAllocation: 0,
    annualFee: 0.10,
  },
  {
    id: 'opt-intl-shares-unhedged',
    name: 'International Shares Unhedged Index',
    category: 'Asset class options',
    riskLevel: 'High',
    returnProfile: 'High',
    currentAllocation: 0,
    annualFee: 0.10,
  },
  {
    id: 'opt-listed-property',
    name: 'Listed Property Index',
    category: 'Asset class options',
    riskLevel: 'High',
    returnProfile: 'High',
    currentAllocation: 0,
    annualFee: 0.10,
  },
  {
    id: 'opt-unlisted-assets',
    name: 'Unlisted Assets',
    category: 'Asset class options',
    riskLevel: 'Medium to high',
    returnProfile: 'Medium to high',
    currentAllocation: 0,
    annualFee: 1.73,
  },
  {
    id: 'opt-bonds',
    name: 'Bonds Index',
    category: 'Asset class options',
    riskLevel: 'Low to medium',
    returnProfile: 'Low',
    currentAllocation: 0,
    annualFee: 0.08,
  },
  {
    id: 'opt-cash',
    name: 'Cash',
    category: 'Asset class options',
    riskLevel: 'Very low',
    returnProfile: 'Low',
    currentAllocation: 0,
    annualFee: 0.07,
  },
];
